version: '3'
services:
  nextcloudpi:
    image: ownyourbits/nextcloudpi-armhf:latest
    command: "rlang.myfirewall.org"
    restart: on-failure:5
    ports:
     - "80:80"
     - "443:443"
     - "4443:4443"
    volumes:
     - /media/data/nextcloudpidata:/data
     - /etc/localtime:/etc/localtime:ro
    container_name: nextcloudpi

